# SPDX-FileCopyrightText: 2020 Theo Dedeken
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE compliant

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check REUSE compliance
        uses: docker://fsfe/reuse
        with:
          args: lint
